db.questions.insert({position: 0, question:"Melyik városunkban látható a Gizella-kápolna?", answers: ["Veszprémben", "Székesfehérvárott", "Gyõrben"], correct:0, asked: false})
db.questions.insert({position: 1, question:"Melyik tudományág nem tartozott bele az ókori hét szabad mûvészetbe?", answers: ["geometria", "asztronómia", "mechanika"], correct:2, asked: false})
db.questions.insert({position: 2, question:"Hol halt meg Horthy Miklós?", answers: ["Portugáliában", "Spanyolországban", "Brazíliában"], correct:0, asked: false})
db.questions.insert({position: 3, question:"Milyen madarak násza szerepel egy ismert Ady-vers címében?", answers: ["sas", "héja", "keselyû"], correct:1, asked: false})
db.questions.insert({position: 4, question:"Melyik város mesterdalnokairól írt operát Wagner?", answers: ["München", "Hamburg", "Nürnberg"], correct:2, asked: false})
db.questions.insert({position: 5, question:"Melyik filmhõs alakítójaként lett világhírû Christopher Reeve?", answers: ["James Bond", "Superman", "Zorro"], correct:1, asked: false})
db.questions.insert({position: 6, question:"Mi az abszolút lehetetlen?", answers: ["-10 kocsma", "Hímvesszõbõl kosarat dobni", "Hepehupás úton egymás után két hepe"], correct:2, asked: false})
db.questions.insert({position: 7, question:"Melyik város ismert szórakozónegyede a Soho?", answers: ["Tokió", "Párizs", "London"], correct:2, asked: false})
db.questions.insert({position: 8, question:"Melyik állam katonai fõparancsnokai voltak a sógunok a középkorban?", answers: ["Japán", "Kína", "India"], correct:0, asked: false})
db.questions.insert({position: 9, question:"Mely ország fizetõeszköze a jüan?", answers: ["Kína", "Japán", "Vietnám"], correct:0, asked: false})
db.questions.insert({position: 10, question:"Honnan ered az akupunktúra mint gyógymód?", answers: ["Kínából", "Indiából", "Japánból"], correct:0, asked: false})
db.questions.insert({position: 11, question:"Hol található Borobudur, a világ legnagyobb buddhista templomegyüttese?", answers: ["India", "Indonézia", "Thaiföld"], correct:1, asked: false})
db.questions.insert({position: 12, question:"Melyik nem ázsiai fõváros az alábbiak közül?", answers: ["Colombo", "Kartúm", "Damaszkusz"], correct:1, asked: false})
db.questions.insert({position: 13, question:"Melyik mû írójának tiszteletére alkották meg a palóclevest?", answers: ["Aranykoporsó", "Rokonok", "Gavallérok"], correct:2, asked: false})
db.questions.insert({position: 14, question:"Hány kocka van a kockásfülû nyúl fülén?", answers: ["35", "26", "0"], correct:2, asked: false})
db.questions.insert({position: 15, question:"Miket választ el egymástól a Kármán-vonal?", answers: ["a légi teret és a világûrt", "a sztratoszférát és a bioszférát", "a kontinenseket és a tengereket"], correct:0, asked: false})
db.questions.insert({position: 16, question:"Ki nem játszotta a legendás James Bondot?", answers: ["Sean Connery", "Timothy Hutton", "George Lazenby"], correct:1, asked: false})
db.questions.insert({position: 17, question:"Melyik együttes slágere volt a 'The Wall'?", answers: ["Pink Floyd", "Genesis", "Rolling Stones"], correct:0, asked: false})
db.questions.insert({position: 18, question:"Mi látható az ötforintos érmén az alábbiak közül?", answers: ["madár", "címer", "virág"], correct:0, asked: false})
db.questions.insert({position: 19, question:"Milyen színû haja van Réti Orsinak?", answers: ["Barna", "Szõke", "De ki az a Mezei Orsi?"], correct:0, asked: false})
db.questions.insert({position: 20, question:"Mi volt az egri Líceum Spekula nevû épülete?", answers: ["kaszinó", "kereskedõház", "csillagvizsgáló"], correct:2, asked: false})
db.questions.insert({position: 21, question:"Kije volt Szent Istvánnak Orseolo Péter, a második magyar király?", answers: ["fia", "unokája", "unokaöccse"], correct:2, asked: false})
db.questions.insert({position: 22, question:"Hogy hívták az Aranycsapat szövetségi kapitányát?", answers: ["Illovszky Rudolf", "Sebes Gusztáv", "Baróti Lajos"], correct:1, asked: false})
db.questions.insert({position: 23, question:"Mi az angol trónörökös hagyományos címe?", answers: ["walesi herceg", "Lord Mayor", "windsori herceg"], correct:0, asked: false})
db.questions.insert({position: 24, question:"Melyik városban van nyár, amikor a másik kettõben tél van?", answers: ["Quebec", "Indianapolis", "Montevideo"], correct:2, asked: false})
db.questions.insert({position: 25, question:"Szerencsés vagy?", answers: ["Yepp", "Igen", "Persze"], correct:1, asked: false})
db.questions.insert({position: 26, question:"A modern kottaírásban hányadik vonalra szokás rajzolni a violinkulcsot?", answers: ["elsõ", "második", "harmadik"], correct:1, asked: false})
db.questions.insert({position: 27, question:"Melyik ország nem szigetország?", answers: ["Sri Lanka", "Tajvan", "Honduras"], correct:2, asked: false})