db.questions.insert({question:"Hol kell leszállni a táborba jövet?", answers: {correct:"Eggyel később mint a későn jövők", wrong1: "Eggyel korábban mint a korábban jövők", wrong2: "Tulipán utca"}, asked: false})
db.questions.insert({question:"Hány kilométert kell sétálni a táborba jövet?", answers: {correct:"4-et", wrong1: "Wico szerint csak 1.5", wrong2: "A balherétől még 2"}, asked: false})
db.questions.insert({question:"Ha felszállsz a buszra, hány banyatank gázol el?", answers: {correct:"Nem élik túl", wrong1: "Úgy is van jegyük!", wrong2: "Mind"}, asked: false})
db.questions.insert({question:"Miből van több a táborban?", answers: {correct:"Alkohol", wrong1: "Víz", wrong2: "Térerő"}, asked: false})
db.questions.insert({question:"Hány állat tűnt el csillagtúrán?", answers: {correct:"Malac", wrong1: "Nyuszi", wrong2: "Cumi"}, asked: false})
db.questions.insert({question:"Hány feles sört ivott meg Máté, amikor csapaton belül versenyeztünk?", answers: {correct:"1", wrong1: "13", wrong2: "38"}, asked: false})
db.questions.insert({question:"Hol tört meg Soleck 'Nem szarok a természetben' szabálya?", answers: {correct:"Helyszínbejárás", wrong1: "Csillagtúra", wrong2: "Osztálykirándulás"}, asked: false})
db.questions.insert({question:"Ki fingott?", answers: {correct:"Cumi", wrong1: "Lizi", wrong2: "Tuba"}, asked: false})
db.questions.insert({question:"Hány órával zár hamarabb a bolt Dinnyésen, mint Máté világában?", answers: {correct:"6", wrong1: "2", wrong2: "4"}, asked: false})
db.questions.insert({question:"Kik dugtak a tavalyi kupavideóban?", answers: {correct:"Eszti+Sau", wrong1: "Eszti+Fanni", wrong2: "Fanni+Kere"}, asked: false})
db.questions.insert({question:"Mikor hagyta abba Cumi a lolozást?", answers: {correct:"Amikor betört a képernyője", wrong1: "Amikor megválasztottuk főrendezőnek", wrong2: "Soha"}, asked: false})
db.questions.insert({question:"Hogy szól helyesen a mondás?", answers: {correct:"Magam alatt ásom a fát", wrong1: "Addig jár Jóska a kútra, amíg iható a víz", wrong2: "A felvettek 50%-ából sose lesz gólya"}, asked: false})
db.questions.insert({question:"Mi az abszolút lehetetlen?", answers: {correct:"Hepehupás úton egymás után két hepe", wrong1: "Hímvesszőből kosarat dobni", wrong2: "-10 kocsma"}, asked: false})
db.questions.insert({question:"Melyik hármas hányt ugyanabban az időben ugyanabba a wc-be?", answers: {correct:"Máté+Szaki+Wico", wrong1: "Cumi+Kere+Soleck", wrong2: "Pke+Lizi+Tuba"}, asked: false})
db.questions.insert({question:"Ki szakadt bele a tóba CST bejáráson?", answers: {correct:"Balázs", wrong1: "Wico", wrong2: "Cumi (merődagadt)"}, asked: false})
db.questions.insert({question:"Mit ivott Kere a villamoson (tavalyi Qpa), amiért beszólt az ellenőr?", answers: {correct:"Tejet", wrong1: "Kannásat", wrong2: "Tiszta vodkát"}, asked: false})
db.questions.insert({question:"Ki és mivel okozott tűzriadót a tavalyi Qpán?", answers: {correct:"Kolos egy kakaóscsigával", wrong1: "Wico a pizzasütővel", wrong2: "Koza a vízipipiával"}, asked: false})
db.questions.insert({question:"Mi a külömbség Szeki, Szaki és Széki között?", answers: {correct:"A nemi identitásuk", wrong1: "Ki a faszom az a Széki?", wrong2: "Két betű"}, asked: false})
db.questions.insert({question:"Szerencsés vagy?", answers: {correct:"Igen", wrong1: "Yepp", wrong2: "Persze"}, asked: false})
db.questions.insert({question:"Kinek van a legnagyobb orra?", answers: {correct:"Matyi", wrong1: "Tuba", wrong2: "Köhn Grünwald"}, asked: false})
db.questions.insert({question:"Kinek van a legnagyobb melle?", answers: {correct:"Soleck", wrong1: "Cumi", wrong2: "Homyx"}, asked: false})
db.questions.insert({question:"35 kockából 14 hármas", answers: {correct:"Nem hiszem el", wrong1: "14 hatos", wrong2: "8 egyes"}, asked: false})
db.questions.insert({question:"Hány kocka van a kockásfülű nyúl fülén?", answers: {correct:"0", wrong1: "26", wrong2: "35"}, asked: false})
db.questions.insert({question:"Mit kínáltunk fel a Bálna őrének azért, hogy bejuthassunk?", answers: {correct:"Croissant", wrong1: "Pénzt", wrong2: "Csapatpólót"}, asked: false})
db.questions.insert({question:"Hány rendező van?", answers: {correct:"57", wrong1: "56", wrong2: "55"}, asked: false})
db.questions.insert({question:"Nem mondod hogy römiztek?", answers: {correct:"De", wrong1: "Nem basztok?", wrong2: "Osszunk neked is?"}, asked: false})
db.questions.insert({question:"Milyen színű haja van Réti Orsinak?", answers: {correct:"Barna", wrong1: "De ki az a Mezei Orsi?", wrong2: "Szőke"}, asked: false})
db.questions.insert({question:"Ez az utolsó kérdés?", answers: {correct:"Ez nem hangzott el órán", wrong1: "Igen", wrong2: "Nem"}, asked: false})
db.questions.insert({question:"Melyik fenyérlakó ízeltlábú él habos váladékburokban?", answers: {correct:"A mezei kabóca nimfalárvája", wrong1: "Szegélyes vidrapók", wrong2: "Szúnyog"}, asked: false})
db.questions.insert({question:"Mit jelent az, hogyha egy hím pávián ásít?", answers: {correct:"Erejét fitoktatja", wrong1: "Szexuális vágyat", wrong2: "Minden bizonnyal álmos"}, asked: false})
db.questions.insert({question:"Ki festette a 'Kalászszedők' képet?", answers: {correct:"Jean-François Milet", wrong1: "Edouard Manet", wrong2: "Gustave Courbet"}, asked: false})